- name: Ansible Playbook to configure a webserver inside a Docker Container!
  hosts: Docker_Webserver
  tasks:
    # Adding the Docker Yum Repository link
    - name: Adding the Yum Repository for Docker
      yum_repository:
        name: Docker-Repo
        file: docker-ce
        description: Configuring the Docker Community Edition repo
        baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
        gpgcheck: no
      register: DockerRepoStatus

    - name: Printing Docker Repo Configuration Status
      debug:
        msg: "Does Configuration Failed: {{ DockerRepoStatus.failed }}"

    - name: Downloading & Installing the Docker Software
      when: DockerRepoStatus.failed == false
      shell: dnf install -y docker-ce --nobest
      args:
        warn: false
      register: DDS

    - name: Printing Docker Installation Success
      debug:
        msg: "Docker Installed: {{ DDS.rc }}   [Yes if 0 , otherwise No]"

    - name: Disabling the Firewalld for Docker Operations with the external entities!
      when: DDS.rc == 0
      service:
        name: firewalld
        state: stopped
      register: Firewall_Status

    - name: Firewall Status
      debug:
        msg: "Firewall Daemon State: {{ Firewall_Status.state }}"


        
