- name: Ansible Playbook to configure a webserver inside a Docker Container!
  hosts: Docker_Webserver
  tasks:
    # Adding the Docker Yum Repository link
    - name: Adding the Yum Repository for Docker
      yum_repository:
        name: Docker-Repo
        file: docker-ce
        description: Configuring the Docker Community Edition repo
        baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
        gpgcheck: no
      register: DockerRepoStatus

    - name: Printing Docker Repo Configuration Status
      debug:
        msg: "Does Configuration Failed: {{ DockerRepoStatus.failed }}"

    - name: Downloading & Installing the Docker Software
      when: DockerRepoStatus.failed == false
      shell: dnf install -y docker-ce --nobest
      args:
        warn: false
      register: DIS

    - name: Printing Docker Installation Success
      debug:
        msg: "Docker Installed: {{ DIS.rc }}   [Yes if 0 , otherwise No]"

    - name: Disabling the Firewalld for Docker Operations with the external entities!
      when: DIS.rc == 0
      service:
        name: firewalld
        state: stopped
      register: Firewall_Status

    - name: Firewall Status
      debug:
        msg: "Firewall Daemon State: {{ Firewall_Status.state }}"

    - name: Starting the Docker Services
      when: DIS.rc == 0
      service:
        name: docker
        state: started
        enabled: yes
      register: Docker_Start_Status

    - name: Printing the Docker Running Status
      debug:
        msg: "Docker Services Enabled & Started {{Docker_Start_Status.state}}"

    - name: Installing Docker-py to support docker pull
      when: Docker_Start_Status.state == started
        pip:
          name: "docker-py"
          state: present
        register: docker_py_status

    - name: Docker-py Status
      debug:
        msg: "Docker Py Download Failed Status => {{ docker_py_status.failed}}"
