- name: PlayBook to configure Yum-Docker-Webserver
  hosts: Database
  tasks:
          # Configuring Yum for Epel Packages
          - name: Configure the Yum with epel
            yum_repository:
                    name: epel
                    file: epel
                    description: Configure the epel repo
                    baseurl: https://dl.fedoraproject.org/pub/epel/7/x86_64/
                    gpgcheck: no
            register: epel_status

          - name: Epel Status
            debug:
                    msg: "Did EPEL Configuration Failed => {{  epel_status.failed }}"


        # Configuring Yum for the Docker Repository
          - name: Configuring Docker Yum Repository
            when: epel_status.failed == false
            yum_repository:
                    name: docker-ce
                    file: docker-ce
                    description: Configure the Docker Community Edition repo
                    baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
                    gpgcheck: no
            register: docker_ce_status

          - name: Docker-CE Status
            debug:
                    msg: "Did Docker Configuration Failed => {{  docker_ce_status.failed }}"


        # Downloading Docker 
          - name: Download Docker-CE 
            when: docker_ce_status.failed == false
            command:
                    cmd: dnf install -y docker-ce --nobest
                    #state: present
            register: docker_install_status

          - name: Docker Installation Status
            debug:
                    msg: "Docker Installation Return Code => {{ docker_install_status.rc }}"


        # Starting the Docker Services
          - name: Start Docker Services
            when: docker_install_status.rc == 0
            service:
                    name: "docker"
                    state: started
                    enabled: yes
            register: docker_service_status

          - name: Docker Service Status
            debug:
                    msg: "Docker Service Status => {{ docker_service_status.state}}"


        # Downloading Docker-py Module for the Docker Pull to run on the managed node!
          - name: Download docker-py Module
            when: docker_service_status.state == "started"
            pip:
                    name: "docker-py"
                    state: present
            register: docker_py_status

          - name: Docker-py Status
            debug:
                    msg: "Docker Py Download Failed Status => {{ docker_py_status.failed}}"


       # Downloading my Own Docker Image of Webserver! 
          - name: Downloading my Webserver Docker Image
            when:
                    - docker_service_status.state == "started" 
                    - docker_py_status.failed == false
            docker_image:
                    name: harshitdawar/apache-webserver-and-php:latest
                    source: pull
                    state: present
            register: docker_imagePull_status
       
          - name: Docker Image Pull Status
            debug:
                    msg: "Docker Image Pull Failed Status => {{ docker_imagePull_status.failed}}"


       # Downloading Httpd Webserver in Host Machine
          - name: Downloading Webserver in Host Machine
            package:
                    name: httpd
                    state: present
            register: httpd_status

          - name: Docker Webserver Container Status
            debug:
                    msg: "Docker webserver Download Failed Status => {{ httpd_status.failed}}"


      # Running the Webserver Docker Container! 
          - name: Running Webserver Container
            when: 
                   - docker_imagePull_status.failed == false
                   - httpd_status.failed == false  
            docker_container:
                    name: webserver
                    image: harshitdawar/apache-webserver-and-php
                    state: started
                    published_ports:
                            - "0.0.0.0:80:80"
            register: docker_container_status

          - name: Docker Webserver Container Status
            debug:
                    msg: "Docker image container Failed Status => {{ docker_container_status.failed}}"


       # Stopping firewall daemon for Docker Container to run smoothly! 
          - name: Disabling Firewall Daemon
            when:
                   - docker_container_status.failed == false
            service:
                    name: firewalld
                    state: stopped
            register: firewalld_status

          - name: Firewall Daemon Status
            debug:
                    msg: "Firewall Daemon Status => {{ firewalld_status}}"

