- name: Playbook to configure the Hadoop Master Node
  vars_files:
    - variables.yml
  hosts: MasterNode
  tasks:
    - name: Creating a directory for the Hadoop Softwares
      file:
        path: "{{ hadoop_dir }}"
        state: directory

    - name: Downloading Hadoop-1.2.1 software
      notify: Installing Hadoop Software
      get_url:
        url: "https://archive.apache.org/dist/hadoop/common/hadoop-1.2.1/hadoop-1.2.1-1.x86_64.rpm"
        dest: "{{ hadoop_dir }}/hadoop-1.2.1-1.x86_64.rpm"


  handlers:
    - name: Installing Hadoop Software
      command: "rpm -ivh {{ hadoop_dir }}/hadoop-1.2.1-1.x86_64.rpm --force"