- name: Ansible-Playbook to Terminate AWS EC2-Instance
  hosts: localhost
  vars_files:
    - password.yaml
  tasks:
    - name: Terminating the already launched AWS Instance
      ec2:
        instance_type: t2.micro
        # Image/AMI ID using which the instance is running 
        image: "ami-08706cb5f68222d09"
        # Instance Id of the EC2-instance which has to be terminated.
        instance_ids:
          - i-08332d0ad3d36b493
        # Wait for the work/task to complete
        wait: yes
        count: 1
        # Subnet ID in which the instance is launched.
        vpc_subnet_id: subnet-44e49308
        # State is assigned to absent, so that the instance is deleted.
        state: absent
        region: ap-south-1
        aws_access_key: "{{ accessKey }}"
        aws_secret_key: "{{ secretKey }}"