---
# tasks file for HAProxy-Load-Balancer
- name: Install HAProxy Software
  package:
    name: "{{ software }}"
    state: present

- name: Copy the haproxy conf file to host
  template:
    src: "haproxy.cfg"
    dest: "/etc/haproxy/haproxy.cfg"
    mode: 0666
  notify: Restarting HAProxy Services

- name: Start the services
  service:
    name: "{{ software }}"
    state: started
    enabled: yes