---
# tasks file for HAProxy-Load-Balancer
- name: Install HAProxy Software
  package:
    name: "{{ software }}"
    state: present

- name: Copy the haproxy conf file to host
  copy:
    src: "Configuration-Files/haproxy.cfg"
    dest: "/etc/haproxy/haproxy.cfg"