- name: Ansible-Playbook to provision AWS EC2-Instance!
  hosts: localhost
  vars_files:
    - password.yaml
  tasks:
    - name: Launching an AWS Instance
      ec2:
        key_name: MyKeyFinal
        instance_type: t2.micro
        image: "ami-08706cb5f68222d09"
        wait: yes
        group_id: "sg-0202966a4cb160463"
        count: 1
        vpc_subnet_id: subnet-44e49308
        assign_public_ip: yes
        state: present
        region: ap-south-1
        aws_access_key: "{{ accessKey }}"
        aws_secret_key: "{{ secretKey }}"
      # Registering all the details of the provisioned Instance in a variable to retrieve Public IP
      register: EC2_Instance

      # Displaying the Public IP of the AWS Instance
    - name: Printing the Details of the Provisioned Instance
      debug:
        msg: "{{ EC2_Instance.public_ip }}"

- name: Ansible-Playbook to Connect to EC2-Instance and Configure it for webserver!
  hosts: "{{ EC2_Instance.public_ip }}"
  tasks:
    - name: Configuring the HTTPD server in the Instance
      become: yes
      become_user: ec2-user
      become_method: sudo
      package:
        name: 
          - httpd
          - php
        state: present
      service:
        name: httpd
        state: started
        enable: yes
      register: Confi

    - name: Printing the Configuration Details
      debug:
        msg: "{{ Confi }}"