- name: PlayBook to configure Kubernetes_Master (Final Configuration of KubeAdm)
  hosts: Kubernetes_Master
  tasks:
# Initializing the Master Node with Kubeadm service
          - name: Initializing Master Node
            shell:
              cmd: kubeadm init --pod-network-cidr=57.1.1.1/16
            register: KubeAdm_status
            ignore_errors: yes

          - name: KubeAdm Status
            debug:
                  msg: "{{ KubeAdm_status }}"
            

        
        # Creating the required sdirectory after Kubeadm init successful
          - name: Creating the required directories
            file:
              path: "mkdir -p $HOME/.kube"
              state: directory
                #- "sudo chown $(id -u):$(id -g) $HOME/.kube/config"
            register: KubeAdm_Commands_status

          - name: KubeAdm Commands Status
            debug:
                  msg: "{{ KubeAdm_Commands_status }}"

          # Copying the required stuff after Kubeadm init successful
          - name: Copy command of KubeAdm
            shell:
              cmd: sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
            register: KubeAdm_CP_Commands_status

          - name: KubeAdm Copy Commands Status
            debug:
                  msg: "{{ KubeAdm_CP_Commands_status }}"

          # Changing the ownership of the directories
          - name: Changing ownership of directories
            shell:
              cmd: sudo chown $(id -u):$(id -g) $HOME/.kube/config
            register: KubeAdm_Changing_Ownership_Commands_status

          - name: KubeAdm Changing ownership Commands Status
            debug:
                  msg: "{{ KubeAdm_Changing_Ownership_Commands_status }}"

        
        # Adding the support of Flannel Network for Overlay Network
          - name: Adding Flannel Network
            command:
              cmd: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
            register: Flannel_status

          - name: Flannel Network Status
            debug:
                msg: "Flannel Network failed => {{ Flannel_status.failed }}"