- name: PlayBook to configure Kubernetes_Master
  hosts: Kubernetes_Master
  tasks:
          # Configuring Yum for Epel Packages
          - name: Configure the Yum with epel
            yum_repository:
                    name: epel
                    file: epel
                    description: Configure the epel repo
                    baseurl: https://dl.fedoraproject.org/pub/epel/7/x86_64/
                    gpgcheck: no
            register: epel_status

          - name: Epel Status
            debug:
                    msg: "Did EPEL Configuration Failed => {{  epel_status.failed }}"


        # Configuring Yum for the Docker Repository
          - name: Configuring Docker Yum Repository
            when: epel_status.failed == false
            yum_repository:
                    name: docker-ce
                    file: docker-ce
                    description: Configure the Docker Community Edition repo
                    baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
                    gpgcheck: no
            register: docker_ce_status

          - name: Docker-CE Status
            debug:
                    msg: "Did Docker Configuration Failed => {{  docker_ce_status.failed }}"

        # Configuring Yum for the kubernetes Repository
          - name: Configuring kubernetes Yum Repository
            yum_repository:
                    name: kubernetes
                    file: kubernetes
                    description: Configure the kubernetes repo
                    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
                    gpgcheck: yes
                    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
            register: kubernetes_status

          - name: Kubernetes Repo Status
            debug:
                    msg: "Did Kubernetes Repo Configuration Failed => {{  kubernetes_status.failed }}"


        # Stopping firewall daemon for Docker Container to run smoothly! 
          - name: Disabling Firewall Daemon
            service:
                    name: firewalld
                    state: stopped
            register: firewalld_status

          - name: Firewall Daemon Status
            debug:
                    msg: "Firewall Daemon Failed State => {{ firewalld_status.state}}"


         # Disabling SELINUX
          - name: Disabling SELINUX
            when: firewalld_status.failed == false
            command:
                    cmd: setenforce 0
                    #state: present
            register: SEL_Disable_status

          - name: SeLinux Disable Status
            debug:
                    msg: "SeLinux Disable Failed Status => {{ SEL_Disable_status.failed }}"